-- Criação das tabelas sem otimização
CREATE TABLE AIR_AIRLINES AS SELECT * FROM ACAMPOS.AIR_AIRLINES;
CREATE TABLE AIR_AIRPLANES AS SELECT * FROM ACAMPOS.AIR_AIRPLANES;
CREATE TABLE AIR_AIRPLANE_TYPES AS SELECT * FROM ACAMPOS.AIR_AIRPLANE_TYPES;
CREATE TABLE AIR_AIRPORTS AS SELECT * FROM ACAMPOS.AIR_AIRPORTS;
CREATE TABLE AIR_AIRPORTS_GEO AS SELECT * FROM ACAMPOS.AIR_AIRPORTS_GEO;
CREATE TABLE AIR_BOOKINGS AS SELECT * FROM ACAMPOS.AIR_BOOKINGS;
CREATE TABLE AIR_FLIGHTS AS SELECT * FROM ACAMPOS.AIR_FLIGHTS;
CREATE TABLE AIR_FLIGHTS_SCHEDULES AS SELECT * FROM ACAMPOS.AIR_FLIGHTS_SCHEDULES;
CREATE TABLE AIR_PASSENGERS AS SELECT * FROM ACAMPOS.AIR_PASSENGERS;
CREATE TABLE AIR_PASSENGERS_DETAILS AS SELECT * FROM ACAMPOS.AIR_PASSENGERS_DETAILS;

-- Reduzir tamanho da tabela de bookings
DELETE FROM AIR_BOOKINGS
WHERE booking_id >= 37088114;
COMMIT;