SELECT /*+ INDEX(f IDX_FLIGHTS_DEPARTURE) */
       b.BOOKING_ID, b.PASSENGER_ID, f.FLIGHT_ID, f.DEPARTURE
FROM AIR_FLIGHTS f
JOIN AIR_BOOKINGS b ON f.FLIGHT_ID = b.FLIGHT_ID
WHERE f.DEPARTURE >= TO_DATE('2023-01-01', 'YYYY-MM-DD')
  AND f.DEPARTURE < TO_DATE('2024-01-01', 'YYYY-MM-DD');