SELECT 
    al.AIRLINE_NAME AS AIRLINE_NAME,
    ap.AIRPLANE_ID,
    apt.NAME AS AIRPLANE_TYPE,
    f.FLIGHT_ID
FROM 
    AIR_FLIGHTS f
    JOIN AIR_AIRLINES al ON f.AIRLINE_ID = al.AIRLINE_ID
    JOIN AIR_AIRPLANES ap ON f.AIRPLANE_ID = ap.AIRPLANE_ID
    JOIN AIR_AIRPLANE_TYPES apt ON ap.AIRPLANE_TYPE_ID = apt.AIRPLANE_TYPE_ID
    JOIN AIR_AIRPORTS dep ON f.FROM_AIRPORT_ID = dep.AIRPORT_ID
    JOIN AIR_AIRPORTS arr ON f.TO_AIRPORT_ID = arr.AIRPORT_ID
    JOIN AIR_AIRPORTS_GEO dep_geo ON dep.AIRPORT_ID = dep_geo.AIRPORT_ID
    JOIN AIR_AIRPORTS_GEO arr_geo ON arr.AIRPORT_ID = arr_geo.AIRPORT_ID
WHERE 
    dep_geo.COUNTRY = 'BRAZIL'
    AND arr_geo.COUNTRY = 'BRAZIL';