SELECT p.PASSENGER_ID, p.FIRSTNAME, p.LASTNAME, d.SEX, 
       FLOOR(MONTHS_BETWEEN(SYSDATE, d.BIRTHDATE) / 12) AS AGE
FROM AIR_PASSENGERS p
JOIN AIR_PASSENGERS_DETAILS d ON p.PASSENGER_ID = d.PASSENGER_ID
WHERE d.SEX = 'w'
  AND FLOOR(MONTHS_BETWEEN(SYSDATE, d.BIRTHDATE) / 12) > 45;