-- Query E: Pré-tuning - sem otimizações específicas
SELECT
    f.FLIGHTNO,
    TO_CHAR(f.DEPARTURE, 'YYYY-MM-DD HH24:MI') AS DEPARTURE_TIME,
    b.SEAT,
    p.FIRSTNAME || ' ' || p.LASTNAME AS PASSENGER_NAME,
    al.AIRLINE_NAME,
    dep.NAME AS DEPARTURE_AIRPORT
FROM 
    AIR_FLIGHTS f
    JOIN AIR_BOOKINGS b ON f.FLIGHT_ID = b.FLIGHT_ID
    JOIN AIR_PASSENGERS p ON b.PASSENGER_ID = p.PASSENGER_ID
    JOIN AIR_AIRLINES al ON f.AIRLINE_ID = al.AIRLINE_ID
    JOIN AIR_AIRPORTS dep ON f.FROM_AIRPORT_ID = dep.AIRPORT_ID
WHERE 
    ROWNUM <= 50
ORDER BY 
    f.DEPARTURE;