SELECT b.BOOKING_ID, b.PASSENGER_ID, f.FLIGHT_ID, f.DEPARTURE
FROM AIR_BOOKINGS b
JOIN AIR_FLIGHTS f ON b.FLIGHT_ID = f.FLIGHT_ID
WHERE f.DEPARTURE >= TO_DATE('2023-01-01', 'YYYY-MM-DD')
  AND f.DEPARTURE < TO_DATE('2024-01-01', 'YYYY-MM-DD');