SELECT 
    f.FLIGHTNO,
    dep.NAME AS DEPARTURE_AIRPORT,
    arr.NAME AS ARRIVAL_AIRPORT,
    p.FIRSTNAME || ' ' || p.LASTNAME AS PASSENGER_NAME,
    b.SEAT
FROM 
    AIR_BOOKINGS b
    JOIN AIR_FLIGHTS f ON b.FLIGHT_ID = f.FLIGHT_ID
    JOIN AIR_AIRPORTS dep ON f.FROM_AIRPORT_ID = dep.AIRPORT_ID
    JOIN AIR_AIRPORTS arr ON f.TO_AIRPORT_ID = arr.AIRPORT_ID
    JOIN AIR_PASSENGERS p ON b.PASSENGER_ID = p.PASSENGER_ID
ORDER BY 
    f.FLIGHTNO, p.FIRSTNAME || ' ' || p.LASTNAME;